In [2]:
import numpy as np

In [3]:
def torus_chebyshev_sum(arr1d, R, C, k):
    arr = arr1d.reshape(R, C)
    # Determine accumulator dtype (avoid overflow for int)
    acc_dtype = np.result_type(arr.dtype, np.int64)
    out = np.zeros((R, C), dtype=acc_dtype)
    
    # Add contributions from all shifts within Chebyshev radius
    for dr in range(-k, k+1):
        for dc in range(-k, k+1):
            out += np.roll(np.roll(arr, dr, axis=0), dc, axis=1)
    
    # Cast back if safe
    if np.issubdtype(arr.dtype, np.integer):
        return out.astype(np.int64 if arr.dtype.itemsize < 8 else arr.dtype)
    else:
        return out.astype(arr.dtype)


In [4]:
R, C, k = 3, 5, 1
arr = np.arange(R*C)

res = torus_chebyshev_sum(arr, R, C, k)
print("Result:\n", res)

# Check value at (0,0)
print("res[0,0] =", res[0,0])

# Manual 3×3 neighborhood sum at (0,0)
arr2d = arr.reshape(R, C)
nbrs = [arr2d[(i%R), (j%C)]
        for i in range(-1, 2)
        for j in range(-1, 2)]
print("Manual check:", sum(nbrs))


Result:
 [[60 54 63 72 66]
 [60 54 63 72 66]
 [60 54 63 72 66]]
res[0,0] = 60
Manual check: 60
